adx_enabletracking: false
adx_excludefromsearch: false
adx_hiddenfromsitemap: false
adx_name: config.js
adx_parentpageid: f5f5af7a-18c4-eb11-bacc-000d3af385d3
adx_partialurl: config.js
adx_publishingstateid: ed67356b-a2db-49a9-b26d-4c8a59e3d9a7
adx_webfileid: bab50d87-1dc4-eb11-bacc-0022483bf7f2
annotationid: bcb50d87-1dc4-eb11-bacc-0022483bf7f2
filename: config.js
isdocument: true
mimetype: application/octet-stream
objectid: bab50d87-1dc4-eb11-bacc-0022483bf7f2
objecttypecode: adx_webfile
