adx_enabletracking: false
adx_excludefromsearch: false
adx_hiddenfromsitemap: false
adx_name: config.js
adx_parentpageid: ff2a6d5f-18c4-eb11-bacc-000d3af385d3
adx_partialurl: config.js
adx_publishingstateid: ed67356b-a2db-49a9-b26d-4c8a59e3d9a7
adx_webfileid: 41f3756d-1dc4-eb11-bacc-0022483bf7f2
annotationid: 43f3756d-1dc4-eb11-bacc-0022483bf7f2
filename: config.js
isdocument: true
mimetype: application/octet-stream
objectid: 41f3756d-1dc4-eb11-bacc-0022483bf7f2
objecttypecode: adx_webfile
