adx_append: false
adx_appendto: false
adx_create: false
adx_delete: false
adx_entitylogicalname: product
adx_entityname: Products
adx_entitypermission_webrole:
- ff54f608-70df-4637-81f7-dc40dc1b7d34
adx_entitypermissionid: cb9d216a-eb9a-4709-8570-e36cab5dcd6c
adx_read: true
adx_scope: 756150000
adx_write: false
