adx_displayorder: 1
adx_enablerating: false
adx_enabletracking: false
adx_excludefromsearch: false
adx_hiddenfromsitemap: false
adx_isroot: false
adx_name: config
adx_pagetemplateid: 460ffba5-bc0c-409e-9674-45523a15dc52
adx_parentpageid: 7fe5f012-14c4-eb11-bacc-000d3af385d3
adx_partialurl: config
adx_publishingstateid: ed67356b-a2db-49a9-b26d-4c8a59e3d9a7
adx_rootwebpageid: a226910d-16c4-eb11-bacc-000d3af385d3
adx_sharedpageconfiguration: true
adx_webpageid: a626910d-16c4-eb11-bacc-000d3af385d3
adx_webpagelanguageid: e9e755c4-c26a-e611-80d7-00155d889a88
