adx_displayorder: 35
adx_enablerating: false
adx_enabletracking: false
adx_entitylist: 2945ecaf-ee30-ec11-b6e6-0022483ccb4c
adx_excludefromsearch: false
adx_feedbackpolicy: 756150000
adx_hiddenfromsitemap: false
adx_isroot: true
adx_name: Products
adx_pagetemplateid: 79d15881-5b2c-ec11-b6e6-0022483c6fb5
adx_parentpageid: 394d2396-7be6-4ee0-bf79-527c8962c7cc
adx_partialurl: products
adx_publishingstateid: ed67356b-a2db-49a9-b26d-4c8a59e3d9a7
adx_sharedpageconfiguration: true
adx_webpageid: d0228110-eb30-ec11-b6e6-0022483ccb4c
